# Keycloak Migration Profile — Generated by Terraform

profile:
  name: ${profile_name}
  environment: terraform-managed

database:
  type: ${db_type}
  location: external
  host: ${db_host}
  port: ${db_port}
  name: ${db_name}
  user: ${db_user}
  credentials_source: env

keycloak:
  deployment_mode: ${deployment_mode}
  distribution_mode: container
  cluster_mode: ${cluster_mode}

  current_version: ${current_version}
  target_version: ${target_version}

%{ if deployment_mode == "kubernetes" || deployment_mode == "deckhouse" ~}
  kubernetes:
    namespace: ${k8s_namespace}
    deployment: ${k8s_deployment}
    service: ${k8s_deployment}-http
    replicas: ${k8s_replicas}
%{ endif ~}

migration:
  strategy: ${migration_strategy}
  parallel_jobs: 4
  timeout_per_version: 900
  run_smoke_tests: true
  backup_before_step: true
